[assets_figures_attractors_rossler_rossler_fig2]
key = "6364719583459948062"
assets = ["assets/figures/attractors/rossler/rossler_fig2.svg"]

[assets_figures_fractals_curves_curves_fig2]
key = "17759767035754928287"
assets = ["assets/figures/fractals/curves/curves_fig2.svg"]

[assets_figures_attractors_lorenz_lorenz_fig3]
key = "7560561049442107703"
assets = ["assets/figures/attractors/lorenz/lorenz_fig3.svg"]

[assets_figures_ising_magnetization_magnetization_fig1]
key = "16149784598153006144"
assets = ["assets/figures/ising/magnetization/magnetization_fig1.svg"]

[assets_figures_fractals_curves_curves_fig1]
key = "11229655035480015512"
assets = ["assets/figures/fractals/curves/curves_fig1.svg"]

[assets_figures_fractals_koch_koch_fig1]
key = "5854365264458024906"
assets = ["assets/figures/fractals/koch/koch_fig1.svg"]

[assets_figures_fractals_koch_koch_fig2]
key = "11603439894471585180"
assets = ["assets/figures/fractals/koch/koch_fig2.svg"]

[assets_figures_fractals_koch_koch_fig3]
key = "6948569472532824585"
assets = ["assets/figures/fractals/koch/koch_fig3.svg"]

[assets_figures_attractors_lorenz_lorenz_fig1]
key = "14237431409837004698"
assets = ["assets/figures/attractors/lorenz/lorenz_fig1.svg"]

[assets_figures_fractals_curves_curves_fig3]
key = "13525342466466088935"
assets = ["assets/figures/fractals/curves/curves_fig3.svg"]

[assets_figures_attractors_lorenz_lorenz_fig2]
key = "4522161573980967656"
assets = ["assets/figures/attractors/lorenz/lorenz_fig2.svg"]

[assets_figures_attractors_rossler_rossler_fig1]
key = "11334858558729932577"
assets = ["assets/figures/attractors/rossler/rossler_fig1.svg"]

[assets_figures_ising_dynamics_dynamics_system_T_2_27__sample_1]
key = "913924135398662175"
assets = ["assets/figures/ising/dynamics/dynamics_system_T_2_27__sample_1.gif"]
