[assets_figures_margins_jl_margins_jl_margins]
key = "5687739857050624634"
assets = ["assets/figures/margins_jl/margins_jl_margins.svg"]

[assets_figures_recovery_jl_recovery_jl_margins]
key = "5687739857050624634"
assets = ["assets/figures/recovery_jl/recovery_jl_margins.svg"]
