[assets_figures_ising_snapshots_snapshots_fig2]
key = "9742958386768002888"
assets = ["assets/figures/ising/snapshots/snapshots_fig2.svg"]

[assets_figures_ising_snapshots_snapshots_fig3]
key = "12587320145649052851"
assets = ["assets/figures/ising/snapshots/snapshots_fig3.svg"]

[assets_figures_ising_snapshots_snapshots_fig1]
key = "194003530643818805"
assets = ["assets/figures/ising/snapshots/snapshots_fig1.svg"]

[assets_figures_ising_magnetization_magnetization_fig1]
key = "6451031763397345735"
assets = ["assets/figures/ising/magnetization/magnetization_fig1.svg"]
